
server.port=8085

alpaca.api.key=PKFPWZM5RPDH76OOD2P5JXQ7BI
alpaca.secret.key=9qutFqhrKtEuA2m94FYYANgPakoGoks2xwiktWHjhdyK
alpaca.base.url=https://paper-api.alpaca.markets/v2
alpaca.news.base.url=https://data.alpaca.markets/v2
agent.interval=3600000

trade.max.qty=5

ollama.url=http://localhost:11434/api/generate
ollama.model=phi3
