
server.port=8085

alpaca.base.url=https://paper-api.alpaca.markets/v2

# IRA-001-A — Robert & Margaret Chen: Traditional IRA
alpaca.account.IRA-001-A.key=PKFPWZM5RPDH76OOD2P5JXQ7BI
alpaca.account.IRA-001-A.secret=9qutFqhrKtEuA2m94FYYANgPakoGoks2xwiktWHjhdyK

# IRA-001-B — Robert & Margaret Chen: Rollover IRA
alpaca.account.IRA-001-B.key=PKIO734SI2AQS6VEGZYWUTSN4E
alpaca.account.IRA-001-B.secret=BUFpKBVRL35RttseT3oi3nHR2wstSLKvTr75xQJRUBHN

# IRA-002-A — William & Dorothy Davis: Traditional IRA
alpaca.account.IRA-002-A.key=PKQ7K7H7UCAKKAUM63R2HOOUJC
alpaca.account.IRA-002-A.secret=9PTRR48WNCLrK3zGWVXecHUGcFvzUEk4DFy7fjDRX7ve

# Default fallback key (same as IRA-001-A)
alpaca.api.key=PKFPWZM5RPDH76OOD2P5JXQ7BI
alpaca.secret.key=9qutFqhrKtEuA2m94FYYANgPakoGoks2xwiktWHjhdyK
alpaca.base.url=https://paper-api.alpaca.markets/v2
alpaca.news.base.url=https://data.alpaca.markets/v2
agent.interval=3600000

trade.max.qty=5

ollama.url=http://localhost:11434/api/generate
ollama.model=phi3
